version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

    volumes:
      - rabbitmq_data:/rabbitmq_data/
    ports:
      - 5672:5672
      - 15672:15672

    restart: always

volumes:
  rabbitmq_data: